kinematics:
  d1: 0.089159
  a2: -0.42500
  a3: -0.39225
  d4: 0.10915
  d5: 0.09465
  d6: 0.0823

  # Arbitrary offsets for shoulder/elbow joints
  shoulder_offset: 0.13585 # measured from model
  elbow_offset: -0.1197 # measured from model

  # link lengths used in model
  shoulder_height: d1
  upper_arm_length: -a2
  forearm_length: -a3
  wrist_1_length: d4 - elbow_offset - shoulder_offset
  wrist_2_length: d5
  wrist_3_length: d6
